---
title: "Untitled"
output: html_document
date: "2025-11-24"
---

```{r}
library(SKAT)
library(ggplot2)
library(dplyr)
library(forcats)
```

```{r}
setid <- read.table("./kawasaki/plink/kegg_genes_lof.SetID", stringsAsFactors = FALSE)
colnames(setid) <- c("Pathway", "SNP") 

setid_unique <- setid[!duplicated(setid$SNP), ]

write.table(setid_unique, "./kawasaki/plink/kegg_genes_lof_clean.SetID",
            quote = FALSE, row.names = FALSE, col.names = FALSE, sep="\t")

```

```{r}
File.Bed = "./kawasaki/plink/kegg_genes_lof_famhis_chd.bed"
File.Bim = "./kawasaki/plink/kegg_genes_lof_famhis_chd.bim"
File.Fam = "./kawasaki/plink/kegg_genes_lof_famhis_chd.fam"
File.SetID = "./kawasaki/plink/kegg_genes_lof_clean.SetID"
File.SSD = "./kawasaki/plink/kegg_genes_lof_famhis_chd.SSD"
File.Info = "./kawasaki/plink/kegg_genes_lof_famhis_chd.SSD.info"
```

```{r}
Generate_SSD_SetID(File.Bed,File.Bim,File.Fam,File.SetID,File.SSD,File.Info)
```

```{r}
FAM = Read_Plink_FAM(File.Fam, Is.binary=FALSE)
y = FAM$Phenotype
```

```{r}
SSD.INFO = Open_SSD(File.SSD, File.Info)
SSD.INFO$nSample
obj = SKAT_Null_Model(y ~ 1, out_type = "D")
SSD.INFO$nSets
out = SKAT.SSD.All(SSD.INFO, obj)
```

```{r}
pathway_summary <- out$results[, c("SetID", "P.value")]
pathway_summary$Variant <- "LoF"
write.table(pathway_summary, 
            file = "./kawasaki/plink/final_lof_famhis_chd.txt", 
            sep = "\t", 
            row.names = FALSE, 
            quote = FALSE)
```



